{% set name = "mapsplice" %}
{% set version = "2.2.1" %}
{% set sha256hash = "4f3c1cb49ba0abcfc952de5946ee0b56db28c51f4f4d4f5abca66b4461ca7d05" %}

package:
  name: {{name}}
  version: {{ version }}

source:
  url: https://protocols.netlab.uky.edu/~zeng/MapSplice-v{{ version }}.zip
  sha256: {{ sha256hash }}
  patches:
    - patches/mapsplice.patch
    - patches/mapsplice_makefile.patch
    - patches/bowtie_makefile.patch
    - patches/samtools.patch
    - patches/samtools_misc.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin = "x") }}

  skip: True # [osx]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - zlib
    - ncurses

  run:
    - python
    - zlib
    - ncurses

test:
  commands:
    - mapsplice.py -v 2>&1 | grep MapSplice > /dev/null

about:
  home: http://www.netlab.uky.edu/p/bioinfo/MapSplice2
  summary: MapSplice is a software for mapping RNA-seq data to reference genome for splice junction discovery that depends only on reference genome, and not on any further annotations.
  license: Custom
  license_file: Copyright.txt

extra:
  additional-platforms:
    - linux-aarch64

  identifiers:
    - biotools:mapsplice
