{% set version = "1.1.alpha19" %}
{% set sha256 = "0e74f3bdaf996c6e54695e23bc2180877f2de0fadc80f0fe9d066aa445b3347c" %}

package:
  name: pplacer
  version: '{{ version }}'

source:
  url: https://github.com/matsen/pplacer/archive/refs/tags/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  skip: true   # [osx]
  number: 3

requirements:
  build:
    - make

  host:
    - ocaml
    - ocamlbuild
    
test:
  commands:
    - pplacer --help > /dev/null
    - guppy to_csv --help > /dev/null
    - rppr check --help > /dev/null

about:
  home: http://matsen.fredhutch.org/pplacer/
  license: GPL-3.0
  license_family: GPL
  summary: Pplacer places query sequences on a fixed reference phylogenetic tree to
    maximize phylogenetic likelihood or posterior probability according to a reference
    alignment.
  dev_url: https://github.com/matsen/pplacer/

extra:
  additional-platforms:
    - linux-aarch64
    
  skip-lints:
    - should_be_noarch_generic
