{% set name = "lambda" %}
{% set version = "3.1.0" %}

package:
  name: {{name}}
  version: {{ version }}

source:
  - url: https://github.com/seqan/lambda/releases/download/lambda-v{{ version }}/lambda3-{{ version }}-SourceWithSubmodules.tar.xz
    sha256: fb3388e8b5a9f33f7423699803eaef4e6b9838c11017bd5b0d2b07f66491f191
    patches:
      - compile-arm.patch
  - url: https://github.com/seqan/sharg-parser/releases/download/1.1.1/sharg-1.1.1-Source.tar.xz
    sha256: 7330f06501718e7871e55e5fd70d0e41472cc8b34bd0e3519f8c5547510c671c
    patches:
      - cstddef.patch
    folder: llvm-sharg

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('lambda', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.0.0,<4
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - make
  host:
    - bzip2
    - seqan-library
    - zlib

test:
  commands:
    - lambda3 --help

about:
  home: http://seqan.github.io/lambda/
  license: AGPLv3
  license_file: LICENSE-AGPL3.rst
  summary: Lambda is a local aligner optimized for many query sequences and searches in protein space
extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
