{% set name = "dashing" %}
{% set version = "1.0.3" %}
{% set sha256 = "8103a7353eb3ca13579766fcb3db778c64c48beaa7e77532778a4ca8cb791655" %}

package:
  name: {{name}}
  version: {{ version }}

build:
  skip: True  # [osx]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin = "x") }}


source:
  url: https://github.com/dnbaker/dashing/archive/refs/tags/v{{version}}.tar.gz
  sha256: {{sha256}}
  patches:
    - popcnt.patch   # [aarch64]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - zstd
    - make
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - dashing --help 2>&1 | grep {{ version }}

about:
  home: https://github.com/dnbaker/dashing
  license: GPL-3
  summary: Fast and accurate genomic distances using HyperLogLog
  license_file: LICENSE

extra:
  additional-platforms:
    - linux-aarch64

  identifiers:
    - doi:10.1101/501726
  recipe-maintainers:
    - silask
    - dnbaker
  skip-lints:
    - uses_vcs_url
